name: varint
description: "A Dart library for encoding and decoding variable-length quantities (VLQ)."
version: 0.0.1+2
homepage: https://github.com/fingerart/varint.dart

topics:
  - vbyte
  - varint
  - vint
  - variable-byte
  - encint

environment:
  sdk: ^3.4.0

dev_dependencies:
  dart_flutter_team_lints: ^3.1.0
  test: ^1.25.8
